### ISSUE TITLE
ボード書き込み時のwarningについて

### ISSUE THREAD

**Issue by takeutchi** [interimadd/NintendoSwitchControll#1]
1. デフォルト引数について
プロトタイプ宣言に記載があるので.cppには不要

1. Missing 'maintainer' from library
`library.properties`に`maintainer`がない

よろしければ修正PR作成します

**Comment by interimadd** [comment]
ご指摘ありがとうございます！
2でwarningが出ていて気になっていた所でした
PR作成よろしくお願いいたします

**Comment by takeutchi** [comment]
pushしたいので権限追加のほどよろしくお願いいたします。

**Comment by interimadd** [comment]
マージしました。対応ありがとうございました
